name: Build
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        name: PHP ${{ matrix.php-versions }} ${{ matrix.composer-args }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['7.3', '7.4', '8.0', '8.1']
                composer-args: ['', '--prefer-lowest']
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.0
            - name: Setup PHP
              uses: shivammathur/setup-php@2.17.0
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring
                  tools: cs2pr
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache dependencies
              uses: actions/cache@v2.1.7
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: php${{ matrix.php-versions }}-composer-${{ matrix.composer-args }}-${{ hashFiles('**/composer.json') }}
                  restore-keys: php${{ matrix.php-versions }}-composer-${{ matrix.composer-args }}-
            - name: Install Dependencies
              run: |
                  composer update --no-progress --no-suggest --prefer-stable --optimize-autoloader ${{ matrix.composer-args }}
            - name: Static Analysis
              run: composer static-analysis
            - name: Code Style Check
              env:
                  PHP_CS_FIXER_IGNORE_ENV: true
              run: composer check-style -- --format=checkstyle | cs2pr
            - name: Test
              run: composer tests
